### PR TITLE
Logic App DevOps Sample: Update nuget, remove unused variables, fix ARM template

### PR DESCRIPTION
**Pull request by liliankasem**
- Removing pipeline variables that are no longer used by the sample
- Upgrading `Microsoft.Azure.Workflows.WebJobs.Extension` to `1.0.0.11-preview`
- Add missing app settings inside the ARM deployment for the logic app

### CODE REVIEW

**Comment by hongzli** [comment]
Hi @liliankasem , could you update the project structure to the new one we release this morning? The project structure has changed to a bundle-based one to improve start time, and also does away with the nuget dependency. You can get the new project structure by updating the Logic Apps (preview) VSCode extension and creating a new project. Let me know if you have any questions.

**Comment by liliankasem** [comment]
@hongzli Happy to do that, but I think there are quite a bit of changes I need to make for this to work with the new version (updates to deploy, pipelines and the project structure itself). I'd like to do that in a different PR so that we can get the bug fixes in fast for the existing sample. Thoughts? @Bec-Lyons

**Comment by hongzli** [comment]
That makes sense. These changes look good to me -- feel free to merge.

**Comment by liliankasem** [comment]
@hongzli I don't have permissions to do that :D

**Comment by hongzli** [comment]
I've merged this one. Let me know when you get a chance to update the project structure to the new one and I can help review/merge that PR as well.

**Comment by liliankasem** [comment]
Awesome, will do! Should get the chance to make the update some time next week

**Pull request merged**
