### PR TITLE
Provide template for handling Azure Monitor Alerts

### LINKED ISSUE #36: Provide template for handling Azure Alerts
Provide a template for handling Azure Alerts.

This template should just have an HTTP trigger with the schema of Azure Alerts so that they can be used in the Logic App to handle them.

I'm willing to pick this one up since I've already done this before.

### PR DESCRIPTION
**Pull request by tomkerkhove**
Provide quickstart template for handling Azure Monitor Alerts which will create a trigger with the Azure Alert schema on it.

Closes #36.

### Icon Suggestion
I would suggest to use the following icon for the api summary:

download

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Example of result:
image

Note that the Compose-step is not included but just to indicate how easy it is to use it.

**Comment by tomkerkhove** [comment]
@kevinlam1 can you assign somebody to review please?

**Comment by derek1ee** [comment]
@kevinlam1 instead of a template should this be a new request kind like event grid/security center ones?

**Comment by tomkerkhove** [comment]
@derek1ee Can you elaborate a bit on what you mean, please?

Something to think about as well is if we need a new category a la `Operations`, if that makes sense ofcourse.

**Comment by derek1ee** [comment]
Since this is essentially a request trigger with schema, what we can do -but requires some code change- is to add a new "kind" of request trigger, currently there are two you see in designer, one for security center and another for event grid, if you select "request"  connector. I think this is better suited for that instead of a template - better discoverability and  consistency.

**Comment by kevinlam1** [comment]
Where did you get this schema from?

Thanks,
Kevin

**Comment by tomkerkhove** [comment]
Based on real-world alerts, there was a page describing this somewhere but can't find it anymore.

**Comment by kevinlam1** [comment]
There's an article that describes how to do this:
https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-action-groups-logic-app
Why did you choose the metric alert over the other two (activity log alert or service health alert)?

**Comment by tomkerkhove** [comment]
Because that was one one we were using. Maybe better to rename the template to reflect this, is that OK?

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by tomkerkhove** [comment]
How shall we proceed with this PR @kevinlam1 	& @derek1ee? Shall I rename it to `Azure Monitor - Metric Alert Handler`?

**Comment by tomkerkhove** [comment]
> There's an article that describes how to do this:
> [docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-action-groups-logic-app](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-action-groups-logic-app)
> Why did you choose the metric alert over the other two (activity log alert or service health alert)?

@kevinlam1 	And to elaborate on why metric - This feels most natural to me to use metrics to alert on given all the information is there.

**Activity log alerts** are more to detect that person X did Y in my opinion while **service health alerts** are to detect unhealthy resources which is not always what we need.

However, they both are useful as well, that's why I would suggest to rename my template to `Azure Monitor - Metric Alert Handler` and merge it in?

**Pull request merged**
