### PR TITLE
Streamline template for handling Azure Monitor metric alerts

### PR DESCRIPTION
**Pull request by tomkerkhove**
Streamline template for handling Azure Monitor metric alerts by:
1. Fixing wrong name in manifest due to rename
2. Point to temporary image, please move this to MSFT location @derek1ee @kevinlam1 	
3. Use new Guid to make sure I generated a new one, but think I did

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thanks for doing a quick fix for now @joechung-msft!

**Comment by joechung-msft** [comment]
Looks good to me.  @derek1ee , can you take a look too?

**Comment by tomkerkhove** [comment]
Don't forget to move the image to a MSFT owned location please!

**Comment by tomkerkhove** [comment]
Thank you for merging @derek1ee!

**Comment by derek1ee** [comment]
@tomkerkhove Thanks for contributing!

**Pull request merged**
